import "./globals.scss";
import Header from "@/components/Header/Header";
import { montserrat, roboto } from "@/fonts";
import "@fortawesome/fontawesome-svg-core/styles.css"
import { Roboto, Montserrat } from "@/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${montserrat.variable}`}>
        <Header/>
        <main>{children}</main>
      </body>
    </html>
  );
}
